In [36]:
#Importing libraries
import pandas as pd
import numpy as np
from google.colab import files

In [37]:
#Uploading and Loading dataset into a dataframe
uploaded = files.upload()

df = pd.read_csv("hotel_bookings.csv")
df.head()

Saving hotel_bookings.csv to hotel_bookings (1).csv

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [38]:
#Dataset overview

print("Dataset Shape:", df.shape)
print("Column Names:")
print(df.columns.tolist())

print("Missing Values:")
print(df.isnull().sum())

Dataset Shape: (119390, 32)
Column Names:
['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date']
Missing Values:
hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [39]:
#Handling Missing Values
df['children'] = df['children'].fillna(0)
df['country'] = df['country'].fillna('Unknown')
df.drop(columns=['agent', 'company'], inplace=True)

print("Checking missing value after data handling")
print(df.isnull().sum())

Checking missing value after data handling
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [40]:
#Creating Intercity Travel Booking Features
np.random.seed(42)

operators=['Green Line', 'Shohag', 'Hanif', 'Ena', 'Saintmartin']
routes =[
        'Dhaka-Ctg',
        'Dhaka-Coxs Bazar',
        'Dhaka-Sylhet',
        'Dhaka-Khulna',
        'Dhaka-Rajshahi'
        ]

df['operator_name'] = np.random.choice(operators, size=len(df))
df['route'] = np.random.choice(routes, size=len(df))
df['seat_type'] = np.random.choice(['Economy', 'Business'],size=len(df),p=[0.8, 0.2])
df['booking_channel'] = np.random.choice(['App', 'Website'],size=len(df),p=[0.7, 0.3])
df['payment_method'] = np.random.choice(['bKash', 'Nagad', 'Card'],size=len(df))
df['number_of_seats'] = (df['adults'] + df['children']).astype(int)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,operator_name,route,seat_type,booking_channel,payment_method,number_of_seats
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,Ena,Dhaka-Rajshahi,Economy,App,Card,2
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,Saintmartin,Dhaka-Khulna,Economy,App,Card,2
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,Hanif,Dhaka-Rajshahi,Economy,Website,bKash,1
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,Saintmartin,Dhaka-Rajshahi,Economy,App,bKash,1
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,1,Check-Out,2015-07-03,Saintmartin,Dhaka-Rajshahi,Economy,App,bKash,2

In [41]:
#Renaming columns
df.rename(columns={
    'adr': 'ticket_price',
    'is_canceled': 'booking_cancelled',
    'lead_time': 'booking_lead_days',
    'is_repeated_guest': 'returning_customer'}, inplace=True)

df.head()

,hotel,booking_cancelled,booking_lead_days,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,operator_name,route,seat_type,booking_channel,payment_method,number_of_seats
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,Ena,Dhaka-Rajshahi,Economy,App,Card,2
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,Saintmartin,Dhaka-Khulna,Economy,App,Card,2
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,Hanif,Dhaka-Rajshahi,Economy,Website,bKash,1
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,Saintmartin,Dhaka-Rajshahi,Economy,App,bKash,1
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,1,Check-Out,2015-07-03,Saintmartin,Dhaka-Rajshahi,Economy,App,bKash,2

In [42]:
#Creating Date Features
df['travel_date'] = pd.to_datetime(
    df['arrival_date_year'].astype(str) + '-' +
    df['arrival_date_month'] + '-' +
    df['arrival_date_day_of_month'].astype(str),
    errors='coerce')

df['booking_date'] = df['travel_date'] - pd.to_timedelta(
    df['booking_lead_days'],
    unit='D')

df['travel_month'] = df['travel_date'].dt.month_name()
df['travel_year'] = df['travel_date'].dt.year
df['travel_day_name'] = df['travel_date'].dt.day_name()

df[['booking_date', 'travel_date', 'travel_month', 'travel_day_name']].head()

  booking_date travel_date travel_month travel_day_name
0   2014-07-24  2015-07-01         July       Wednesday
1   2013-06-24  2015-07-01         July       Wednesday
2   2015-06-24  2015-07-01         July       Wednesday
3   2015-06-18  2015-07-01         July       Wednesday
4   2015-06-17  2015-07-01         July       Wednesday

In [43]:
#Creating Revenue and KPI Column
df['revenue'] = df['ticket_price'] * df['number_of_seats']
df['booking_status'] = np.where(df['booking_cancelled'] == 1,'Cancelled','Completed')
df['customer_segment'] = np.where(df['returning_customer'] == 1,'Returning Customer','New Customer')
df['coupon_used'] = np.random.choice(['Yes', 'No'],size=len(df),p=[0.35, 0.65])

df.head()

,hotel,booking_cancelled,booking_lead_days,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,number_of_seats,travel_date,booking_date,travel_month,travel_year,travel_day_name,revenue,booking_status,customer_segment,coupon_used
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,2,2015-07-01,2014-07-24,July,2015,Wednesday,0.0,Completed,New Customer,No
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,2,2015-07-01,2013-06-24,July,2015,Wednesday,0.0,Completed,New Customer,No
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,1,2015-07-01,2015-06-24,July,2015,Wednesday,75.0,Completed,New Customer,No
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,1,2015-07-01,2015-06-18,July,2015,Wednesday,75.0,Completed,New Customer,No
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,2,2015-07-01,2015-06-17,July,2015,Wednesday,196.0,Completed,New Customer,No

In [44]:
#Final columns for my analytics
final_columns = [
    'booking_date',
    'travel_date',
    'travel_year',
    'travel_month',
    'travel_day_name',
    'route',
    'operator_name',
    'seat_type',
    'booking_channel',
    'payment_method',
    'customer_segment',
    'country',
    'booking_lead_days',
    'number_of_seats',
    'ticket_price',
    'revenue',
    'booking_cancelled',
    'booking_status',
    'coupon_used',
    'market_segment',
    'customer_type',
    'previous_cancellations',
    'booking_changes',
    'deposit_type',
    'total_of_special_requests'
]

travel_df = df[final_columns].copy()

travel_df.head()

,booking_date,travel_date,travel_year,travel_month,travel_day_name,route,operator_name,seat_type,booking_channel,payment_method,...,revenue,booking_cancelled,booking_status,coupon_used,market_segment,customer_type,previous_cancellations,booking_changes,deposit_type,total_of_special_requests
0,2014-07-24,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Ena,Economy,App,Card,...,0.0,0,Completed,No,Direct,Transient,0,3,No Deposit,0
1,2013-06-24,2015-07-01,2015,July,Wednesday,Dhaka-Khulna,Saintmartin,Economy,App,Card,...,0.0,0,Completed,No,Direct,Transient,0,4,No Deposit,0
2,2015-06-24,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Hanif,Economy,Website,bKash,...,75.0,0,Completed,No,Direct,Transient,0,0,No Deposit,0
3,2015-06-18,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Saintmartin,Economy,App,bKash,...,75.0,0,Completed,No,Corporate,Transient,0,0,No Deposit,0
4,2015-06-17,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Saintmartin,Economy,App,bKash,...,196.0,0,Completed,No,Online TA,Transient,0,0,No Deposit,1

In [46]:
#Initial Data Quality Check
print("Dataset Shape:", travel_df.shape)
print("\nMissing Values:")
print(travel_df.isnull().sum())
print("\nDuplicate Rows:", travel_df.duplicated().sum())

travel_df.describe()

Dataset Shape: (119390, 25)

Missing Values:
booking_date                 0
travel_date                  0
travel_year                  0
travel_month                 0
travel_day_name              0
route                        0
operator_name                0
seat_type                    0
booking_channel              0
payment_method               0
customer_segment             0
country                      0
booking_lead_days            0
number_of_seats              0
ticket_price                 0
revenue                      0
booking_cancelled            0
booking_status               0
coupon_used                  0
market_segment               0
customer_type                0
previous_cancellations       0
booking_changes              0
deposit_type                 0
total_of_special_requests    0
dtype: int64

Duplicate Rows: 1025

,booking_date,travel_date,travel_year,booking_lead_days,number_of_seats,ticket_price,revenue,booking_cancelled,previous_cancellations,booking_changes,total_of_special_requests
count,119390,119390,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,2016-05-16 16:23:19.353379840,2016-08-28 16:39:45.727447808,2016.156554,104.011416,1.960290,101.831122,212.913017,0.370416,0.087118,0.221124,0.571363
min,2013-06-24 00:00:00,2015-07-01 00:00:00,2015.000000,0.000000,0.000000,-6.380000,-12.760000,0.000000,0.000000,0.000000,0.000000
25%,2015-11-28 00:00:00,2016-03-13 00:00:00,2016.000000,18.000000,2.000000,69.290000,120.000000,0.000000,0.000000,0.000000,0.000000
50%,2016-05-04 00:00:00,2016-09-06 00:00:00,2016.000000,69.000000,2.000000,94.575000,177.600000,0.000000,0.000000,0.000000,0.000000
75%,2016-12-09 00:00:00,2017-03-18 00:00:00,2017.000000,160.000000,2.000000,126.000000,252.000000,1.000000,0.000000,0.000000,1.000000
max,2017-08-31 00:00:00,2017-08-31 00:00:00,2017.000000,737.000000,55.000000,5400.000000,10800.000000,1.000000,26.000000,21.000000,5.000000
std,NaN,NaN,0.707476,106.863097,0.713053,50.535790,166.170061,0.482918,0.844336,0.652306,0.792798

In [47]:
#Removing Invalid Records Records
print("Shape before cleaning:", travel_df.shape)

travel_df.drop_duplicates(inplace=True)
travel_df = travel_df[travel_df['ticket_price'] > 0]
travel_df = travel_df[travel_df['number_of_seats'] > 0]
travel_df['revenue'] = travel_df['ticket_price'] * travel_df['number_of_seats']

print("Shape after cleaning:", travel_df.shape)
print("Minimum Ticket Price:", travel_df['ticket_price'].min())
print("Minimum Number of Seats:", travel_df['number_of_seats'].min())

Shape before cleaning: (119390, 25)
Shape after cleaning: (116374, 25)
Minimum Ticket Price: 0.26
Minimum Number of Seats: 1

In [48]:
#Creating New Business Features

travel_df['occupancy_category'] = np.where(travel_df['number_of_seats'] >= 3,'Group Booking','Individual Booking')

travel_df['loyalty_status'] = np.where(travel_df['customer_segment'] == 'Returning Customer','Loyal','New')

travel_df['trip_type'] = np.where(travel_df['route'].isin(['Dhaka-Coxs Bazar', 'Dhaka-Sylhet']),'Long Distance','Regular Route')

travel_df['revenue_category'] = pd.cut(travel_df['revenue'],bins=[0, 150, 300, 600, float('inf')],labels=['Low', 'Medium', 'High', 'Premium'])

travel_df.head()

,booking_date,travel_date,travel_year,travel_month,travel_day_name,route,operator_name,seat_type,booking_channel,payment_method,...,market_segment,customer_type,previous_cancellations,booking_changes,deposit_type,total_of_special_requests,occupancy_category,loyalty_status,trip_type,revenue_category
2,2015-06-24,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Hanif,Economy,Website,bKash,...,Direct,Transient,0,0,No Deposit,0,Individual Booking,New,Regular Route,Low
3,2015-06-18,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Saintmartin,Economy,App,bKash,...,Corporate,Transient,0,0,No Deposit,0,Individual Booking,New,Regular Route,Low
4,2015-06-17,2015-07-01,2015,July,Wednesday,Dhaka-Rajshahi,Saintmartin,Economy,App,bKash,...,Online TA,Transient,0,0,No Deposit,1,Individual Booking,New,Regular Route,Medium
5,2015-06-17,2015-07-01,2015,July,Wednesday,Dhaka-Coxs Bazar,Shohag,Economy,App,bKash,...,Online TA,Transient,0,0,No Deposit,1,Individual Booking,New,Long Distance,Medium
6,2015-07-01,2015-07-01,2015,July,Wednesday,Dhaka-Khulna,Hanif,Economy,App,bKash,...,Direct,Transient,0,0,No Deposit,0,Individual Booking,New,Regular Route,Medium

In [50]:
#Data Quality Check
travel_df.info()
travel_df.describe()

print("Missing Values:")
print(travel_df.isnull().sum())

print("Duplicate Rows:")
print(travel_df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
Index: 116374 entries, 2 to 119389
Data columns (total 29 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   booking_date               116374 non-null  datetime64[ns]
 1   travel_date                116374 non-null  datetime64[ns]
 2   travel_year                116374 non-null  int32
 3   travel_month               116374 non-null  object
 4   travel_day_name            116374 non-null  object
 5   route                      116374 non-null  object
 6   operator_name              116374 non-null  object
 7   seat_type                  116374 non-null  object
 8   booking_channel            116374 non-null  object
 9   payment_method             116374 non-null  object
 10  customer_segment           116374 non-null  object
 11  country                    116374 non-null  object
 12  booking_lead_days          116374 non-null  int64
 13  number_of_seats            116374 non-null  int64
 14  ticket_price               116374 non-null  float64
 15  revenue                    116374 non-null  float64
 16  booking_cancelled          116374 non-null  int64
 17  booking_status             116374 non-null  object
 18  coupon_used                116374 non-null  object
 19  market_segment             116374 non-null  object
 20  customer_type              116374 non-null  object
 21  previous_cancellations     116374 non-null  int64
 22  booking_changes            116374 non-null  int64
 23  deposit_type               116374 non-null  object
 24  total_of_special_requests  116374 non-null  int64
 25  occupancy_category         116374 non-null  object
 26  loyalty_status             116374 non-null  object
 27  trip_type                  116374 non-null  object
 28  revenue_category           116374 non-null  category
dtypes: category(1), datetime64[ns](2), float64(2), int32(1), int64(6), object(17)
memory usage: 25.4+ MB
Missing Values:
booking_date                 0
travel_date                  0
travel_year                  0
travel_month                 0
travel_day_name              0
route                        0
operator_name                0
seat_type                    0
booking_channel              0
payment_method               0
customer_segment             0
country                      0
booking_lead_days            0
number_of_seats              0
ticket_price                 0
revenue                      0
booking_cancelled            0
booking_status               0
coupon_used                  0
market_segment               0
customer_type                0
previous_cancellations       0
booking_changes              0
deposit_type                 0
total_of_special_requests    0
occupancy_category           0
loyalty_status               0
trip_type                    0
revenue_category             0
dtype: int64
Duplicate Rows:
0

In [51]:
#Exporting Final Dataset
travel_df.to_csv("intercity_travel_booking_analytics.csv",index=False)

print("Dataset exported successfully")

Dataset exported successfully

In [52]:
from google.colab import files
files.download("intercity_travel_booking_analytics.csv")